name: Generate Datas

on:
  schedule: # execute every 1 hours
    - cron: "* 1/1 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
         github_user_name: joaovictor09
         svg_out_path: dist/github-contribution-grid-snake.svg
